---
- name: Create or update infrastructure
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
  - name: Create AWS VM
    include_role:
      name: terraform
      tasks_from: apply
    vars:
      terraform_apply_state: "present"
      target_module: "aws-vm"
